name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  test-provisioning:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_COUPA_CLIENT_ID: "${{ secrets.BATON_COUPA_CLIENT_ID }}"
      BATON_COUPA_CLIENT_SECRET: "${{ secrets.BATON_COUPA_CLIENT_SECRET }}"
      BATON_COUPA_DOMAIN: "${{ secrets.BATON_COUPA_DOMAIN }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-coupa
        run: go build ./cmd/baton-coupa
      - name: Test roles provisioning
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: ./baton-coupa
          baton-entitlement: 'role:4:member'
          baton-principal: '${{ secrets.CONNECTOR_PRINCIPAL }}'
          baton-principal-type: 'user'
      - name: Test groups provisioning
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: ./baton-coupa
          baton-entitlement: 'group:2:member'
          baton-principal: '${{ secrets.CONNECTOR_PRINCIPAL }}'
          baton-principal-type: 'user'
      - name: Test licenses provisioning
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: ./baton-coupa
          baton-entitlement: 'license:treasury_user:assigned'
          baton-principal: '${{ secrets.CONNECTOR_PRINCIPAL }}'
          baton-principal-type: 'user'
      - name: Test account groups provisioning
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: ./baton-coupa
          baton-entitlement: 'account_group:${{ secrets.BATON_ACCOUNT_GROUP_TEST_ID }}:member'
          baton-principal: '${{ secrets.CONNECTOR_PRINCIPAL }}'
          baton-principal-type: 'user'
  test-actions:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_COUPA_CLIENT_ID: "${{ secrets.BATON_COUPA_CLIENT_ID }}"
      BATON_COUPA_CLIENT_SECRET: "${{ secrets.BATON_COUPA_CLIENT_SECRET }}"
      BATON_COUPA_DOMAIN: "${{ secrets.BATON_COUPA_DOMAIN }}"
      BATON_STATUS_TEST_USER_ID: "${{ secrets.BATON_STATUS_TEST_USER_ID }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-coupa
        run: go build ./cmd/baton-coupa
      - name: Test Account Status Changes
        uses: ConductorOne/github-workflows/actions/account-status-lifecycle-test@v4
        with:
          connector: './baton-coupa'
          account-id: '${{ env.BATON_STATUS_TEST_USER_ID }}'
          enable-action-name: 'enable_user'
          disable-action-name: 'disable_user'
          id-parameter-name: 'user_id'
